services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: unless-stopped
    command: --bind_ip 0.0.0.0
    env_file:
      - .env
    volumes:
      - mongodbdata:/data/db
      - mongodbdata:/data/configdb
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "27017/udp"
      - "27017/tcp"
    networks:
      default:
        ipv4_address: ${MONGO_IP}
        ipv6_address: ${MONGO_IP6}
  webui:
    image: cloudorz/open5gs:2.7.7
    container_name: webui
    restart: unless-stopped
    depends_on:
      - mongo
    env_file:
      - .env
    environment:
      - COMPONENT_NAME=webui
    volumes:
      - ./webui:/mnt/webui
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "9999/tcp"
    ports:
      - "9999:9999/tcp"
    networks:
      default:
        ipv4_address: ${WEBUI_IP}
        ipv6_address: ${WEBUI_IP6}
  hss:
    image: cloudorz/open5gs:2.7.7
    container_name: hss
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - COMPONENT_NAME=hss
    volumes:
      - ./hss:/mnt/hss
      - ./log:/open5gs/install/var/log/open5gs
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - mongo
    expose:
      - "3868/tcp"
      - "3868/sctp"
      - "5868/tcp"
      - "5868/sctp"
    networks:
      default:
        ipv4_address: ${HSS_IP}
        ipv6_address: ${HSS_IP6}
  sgwc:
    image: cloudorz/open5gs:2.7.7
    depends_on:
      - smf
      - upf
    container_name: sgwc
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - COMPONENT_NAME=sgwc
    volumes:
      - ./sgwc:/mnt/sgwc
      - ./log:/open5gs/install/var/log/open5gs
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "2123/udp"
      - "8805/udp"
    networks:
      default:
        ipv4_address: ${SGWC_IP}
        ipv6_address: ${SGWC_IP6}
  sgwu:
    image: cloudorz/open5gs:2.7.7
    depends_on:
      - smf
      - upf
    container_name: sgwu
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - COMPONENT_NAME=sgwu
    volumes:
      - ./sgwu:/mnt/sgwu
      - ./log:/open5gs/install/var/log/open5gs
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "8805/udp"
      - "2152/udp"
    ports:
      - "2152:2152/udp"
    networks:
      default:
        ipv4_address: ${SGWU_IP}
        ipv6_address: ${SGWU_IP6}
  smf:
    image: cloudorz/open5gs:2.7.7
    container_name: smf
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - COMPONENT_NAME=smf
      - DEPLOY_MODE=4G
    volumes:
      - ./smf:/mnt/smf
      - ./log:/open5gs/install/var/log/open5gs
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "3868/tcp"
      - "3868/sctp"
      - "5868/tcp"
      - "5868/sctp"
      - "8805/udp"
      - "2123/udp"
      - "7777/tcp"
      - "9091/tcp"
    networks:
      default:
        ipv4_address: ${SMF_IP}
        ipv6_address: ${SMF_IP6}
  upf:
    image: cloudorz/open5gs:2.7.7
    depends_on:
      - smf
    container_name: upf
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - COMPONENT_NAME=upf
    volumes:
      - ./upf:/mnt/upf
      - ./log:/open5gs/install/var/log/open5gs
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "2152/udp"
      - "8805/udp"
      - "9091/tcp"
    cap_add:
      - NET_ADMIN
    privileged: true
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.all.forwarding=1
    networks:
      default:
        ipv4_address: ${UPF_IP}
        ipv6_address: ${UPF_IP6}
  mme:
    image: cloudorz/open5gs:2.7.7
    depends_on:
      - hss
      - sgwc
      - sgwu
      - smf
      - upf
#      - osmomsc
    container_name: mme
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - COMPONENT_NAME=mme
    volumes:
      - ./mme:/mnt/mme
      - ./log:/open5gs/install/var/log/open5gs
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "3868/tcp"
      - "3868/sctp"
      - "5868/tcp"
      - "5868/sctp"
      - "36412/sctp"
      - "2123/udp"
      - "9091/tcp"
    ports:
      - "36412:36412/sctp"
    networks:
      default:
        ipv4_address: ${MME_IP}
        ipv6_address: ${MME_IP6}
  pcrf:
    image: cloudorz/open5gs:2.7.7
    container_name: pcrf
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - COMPONENT_NAME=pcrf
    depends_on:
      - mongo
    volumes:
      - ./pcrf:/mnt/pcrf
      - ./log:/open5gs/install/var/log/open5gs
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "${PCRF_BIND_PORT}/tcp"
      - "${PCRF_BIND_PORT}/sctp"
      - "5868/tcp"
      - "5868/sctp"
    networks:
      default:
        ipv4_address: ${PCRF_IP}
        ipv6_address: ${PCRF_IP6}
  dns:
    build: ./dns
    image: docker_dns
    container_name: dns
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./dns:/mnt/dns
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "53/udp"
    networks:
      default:
        ipv4_address: ${DNS_IP}
        ipv6_address: ${DNS_IP6}
  rtpengine:
    image: cloudorz/rtpengine:mr13.5.1.16
    container_name: rtpengine
    restart: unless-stopped
    entrypoint: ["/mnt/rtpengine/rtpengine_init.sh"]
    privileged: true
    env_file:
      - .env
    volumes:
      - ./rtpengine:/mnt/rtpengine
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    cap_add:
      - NET_ADMIN
    environment:
      - TABLE=0
      - INTERFACE=${RTPENGINE_IP}
      - INTERFACE6=${RTPENGINE_IP6}
      - LISTEN_NG=${RTPENGINE_IP}:2223
      - PIDFILE=/run/ngcp-rtpengine-daemon.pid
      - PORT_MAX=50000
      - PORT_MIN=49000
      - NO_FALLBACK=no
      - TOS=184
    expose:
      - "2223/udp"
      # - "49000-50000/udp"
    networks:
      default:
        ipv4_address: ${RTPENGINE_IP}
        ipv6_address: ${RTPENGINE_IP6}
  mysql:
    build: ./mysql
    image: docker_mysql
    container_name: mysql
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - dbdata:/var/lib/mysql
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "3306/tcp"
    networks:
      default:
        ipv4_address: ${MYSQL_IP}
        ipv6_address: ${MYSQL_IP6}
  pyhss:
    image: cloudorz/pyhss:1.0.2
    container_name: pyhss
    restart: unless-stopped
    dns: ${DNS_IP}
    volumes:
      - ./pyhss:/mnt/pyhss
      - ./pyhss/logs:/pyhss/log/
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - dns
      - mysql
    expose:
      - "${PYHSS_BIND_PORT}/tcp"
      - "${PYHSS_BIND_PORT}/sctp"
      - "8080/tcp"
    ports:
      - "8080:8080/tcp"
    networks:
      default:
        ipv4_address: ${PYHSS_IP}
        ipv6_address: ${PYHSS_IP6}
  pyhss-gui:
    image: ghcr.io/zarya/pyhss-gui:master
    container_name: pyhss-gui
    restart: unless-stopped
    depends_on:
      - pyhss
    ports:
      - "8999:80/tcp"
    networks:
      default:
        ipv4_address: ${PYHSS_GUI_IP}
        ipv6_address: ${PYHSS_GUI_IP6}
  freeswitch:
    image: cloudorz/freeswitch:1.11.1
    container_name: freeswitch
    restart: unless-stopped
    dns: ${DNS_IP}
    entrypoint: ["sh", "/mnt/freeswitch/freeswitch_init.sh"]
    volumes:
      - ./freeswitch:/mnt/freeswitch
      - ./aibot/shared:/shared
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - dns
      - scscf
    networks:
      default:
        ipv4_address: ${FREESWITCH_IP}
        ipv6_address: ${FREESWITCH_IP6}
  voice-bridge:
    image: open5gs_voicebridge
    container_name: voice-bridge
    restart: unless-stopped
    dns: 8.8.8.8
    env_file:
      - .env
      - ./aibot/voice_secrets.env
    depends_on:
      - freeswitch
    networks:
      default:
        ipv4_address: ${VOICEBRIDGE_IP}
        ipv6_address: ${VOICEBRIDGE_IP6}
  icscf:
    image: cloudorz/kamailio:6.1.3
    container_name: icscf
    restart: unless-stopped
    dns: ${DNS_IP}
    volumes:
      - ./icscf:/mnt/icscf
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    environment:
      - COMPONENT_NAME=icscf
    depends_on:
      - dns
      - mysql
      - pyhss
    expose:
      - "${ICSCF_BIND_PORT}/tcp"
      - "${ICSCF_BIND_PORT}/sctp"
      - "4060/udp"
      - "4060/tcp"
    networks:
      default:
        ipv4_address: ${ICSCF_IP}
        ipv6_address: ${ICSCF_IP6}
  scscf:
    image: cloudorz/kamailio:6.1.3
    container_name: scscf
    restart: unless-stopped
    dns: ${DNS_IP}
    volumes:
      - ./scscf:/mnt/scscf
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    environment:
      - COMPONENT_NAME=scscf
    depends_on:
      - dns
      - mysql
      - pyhss
    expose:
      - "${SCSCF_BIND_PORT}/tcp"
      - "${SCSCF_BIND_PORT}/sctp"
      - "6060/udp"
      - "6060/tcp"
    networks:
      default:
        ipv4_address: ${SCSCF_IP}
        ipv6_address: ${SCSCF_IP6}
  pcscf:
    image: cloudorz/kamailio:6.1.3
    container_name: pcscf
    restart: unless-stopped
    dns: ${DNS_IP}
    privileged: true
    cap_add:
      - NET_ADMIN
    volumes:
      - ./pcscf:/mnt/pcscf
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    environment:
      - COMPONENT_NAME=pcscf
      - DEPLOY_MODE=4G
    depends_on:
      - dns
      - mysql
      - rtpengine
      - icscf
      - scscf
    expose:
      - "${PCSCF_BIND_PORT}/tcp"
      - "${PCSCF_BIND_PORT}/sctp"
      - "5060/tcp"
      - "5060/udp"
      # - "5100-5120/tcp"
      # - "5100-5120/udp"
      # - "6100-6120/tcp"
      # - "6100-6120/udp"
    networks:
      default:
        ipv4_address: ${PCSCF_IP}
        ipv6_address: ${PCSCF_IP6}
  smsc:
    image: cloudorz/kamailio:6.1.3
    container_name: smsc
    restart: unless-stopped
    dns: ${DNS_IP}
    volumes:
      - ./smsc:/mnt/smsc
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    environment:
      - COMPONENT_NAME=smsc
    depends_on:
      - dns
      - mysql
    expose:
      - "7090/udp"
      - "7090/tcp"
    networks:
      default:
        ipv4_address: ${SMSC_IP}
        ipv6_address: ${SMSC_IP6}
#  osmomsc:
#    build: ./osmomsc
#    image: docker_osmomsc
#    container_name: osmomsc
#    restart: unless-stopped
#    volumes:
#      - ./osmomsc:/mnt/osmomsc
#      - /etc/timezone:/etc/timezone:ro
#      - /etc/localtime:/etc/localtime:ro
#    env_file:
#      - .env
#    environment:
#      - COMPONENT_NAME=osmomsc
#    depends_on:
#      - osmohlr
#    expose:
#      - "29118/sctp"
#      - "2775/tcp"
#    networks:
#      default:
#        ipv4_address: ${OSMOMSC_IP}
#        ipv6_address: ${OSMOMSC_IP6}
#  osmohlr:
#    build: ./osmohlr
#    image: docker_osmohlr
#    container_name: osmohlr
#    restart: unless-stopped
#    volumes:
#      - ./osmohlr:/mnt/osmohlr
#      - /etc/timezone:/etc/timezone:ro
#      - /etc/localtime:/etc/localtime:ro
#    env_file:
#      - .env
#    environment:
#      - COMPONENT_NAME=osmohlr
#    expose:
#      - "4222/tcp"
#    networks:
#      default:
#        ipv4_address: ${OSMOHLR_IP}
#        ipv6_address: ${OSMOHLR_IP6}
  metrics:
    build: ./metrics
    image: docker_metrics
    container_name: metrics
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./metrics:/mnt/metrics
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "${METRICS_BIND_PORT}/tcp"
    ports:
      - "${METRICS_BIND_PORT}:${METRICS_BIND_PORT}/tcp"
    networks:
      default:
        ipv4_address: ${METRICS_IP}
        ipv6_address: ${METRICS_IP6}
  grafana:
    image: grafana/grafana:11.3.0
    container_name: grafana
    env_file:
      - .env
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/:/etc/grafana/provisioning/
      - ./grafana:/mnt/grafana
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      #- GF_INSTALL_PLUGINS=${GRAFANA_INSTALL_PLUGINS}
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_PATHS_DATA=/var/lib/grafana
      - METRICS_IP=${METRICS_IP}
    expose:
      - "3000/tcp"
    ports:
      - "3000:3000/tcp"
    networks:
      default:
        ipv4_address: ${GRAFANA_IP}
        ipv6_address: ${GRAFANA_IP6}
networks:
  default:
    name: docker_open5gs_default
    enable_ipv6: true
    ipam:
      config:
        - subnet: ${TEST_NETWORK}
        - subnet: ${TEST_NETWORK6}
          gateway: ${TEST_NETWORK6_GW}
volumes:
  grafana_data:
    name: grafana_data
  mongodbdata:
    name: docker_open5gs_mongodbdata
  dbdata:
    name: docker_open5gs_dbdata
